USE myapp;
DROP TABLE IF EXISTS users;
CREATE TABLE users(
    id INT AUTO_INCREMENT,
    login VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password text NOT NULL,
    PRIMARY KEY(id)
);
